table DynamicMVAnomalySummary
	lineageTag: f6dd6de1-480f-4bf4-bdcf-74cf4d8a03ae

	measure 'Contribution Metric' =
			
			VAR selectedMetric = SELECTEDVALUE(MVADTagContributionOptions[Metric])
			RETURN SWITCH(selectedMetric,"weighted_score", SUM(DynamicMVAnomalySummary[weighted_score]), "average", SUM(DynamicMVAnomalySummary[average]))
		lineageTag: c289c117-2dd4-477a-86a8-508ea4538b39

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MVATagContributionChartTitle = "Contribution to Multivariate Anomaly by " & SELECTEDVALUE(MVADTagContributionOptions[Label])
		lineageTag: 6db884de-cd8d-4e72-9b09-258922035220

	column tag
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 3a0b0092-9a22-4d22-bc57-06fc3ac47d81
		summarizeBy: none
		sourceColumn: tag

		annotation SummarizationSetBy = Automatic

	column secondary_tag
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 443cfd1f-77a0-43a1-a4e0-1cf922220a29
		summarizeBy: none
		sourceColumn: secondary_tag

		annotation SummarizationSetBy = Automatic

	column records
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 716c7e0f-8b37-4ca1-8727-898fe48a09da
		summarizeBy: sum
		sourceColumn: records

		annotation SummarizationSetBy = Automatic

	column weighted_score
		dataType: double
		sourceProviderType: double
		lineageTag: 51c7b579-c79c-413d-8914-affc8120838d
		summarizeBy: sum
		sourceColumn: weighted_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column average
		dataType: double
		sourceProviderType: double
		lineageTag: 06a98508-b987-4055-8975-250747a7255a
		summarizeBy: sum
		sourceColumn: average

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column minimum
		dataType: double
		sourceProviderType: double
		lineageTag: c34aa77d-2ee2-4126-8605-da9567daedc2
		summarizeBy: sum
		sourceColumn: minimum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column maximum
		dataType: double
		sourceProviderType: double
		lineageTag: c5f68189-c7b7-46a9-a849-23469353037a
		summarizeBy: sum
		sourceColumn: maximum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DynamicMVAnomalySummary = m
		mode: directQuery
		source = ```
				let
				    _tags = 
				    if 
				    //check to see if the parameter is a list
				      Type.Is(
				        Value.Type(_tag), 
				        List.Type
				      ) then 
				        //if it is a list
				        let
				          //add single quotes around each value in the list
				          AddSingleQuotes = List.Transform(
				              _tag, 
				              each "'" & _ & "'"
				            ),
				          //then turn it into a comma-delimited list
				          DelimitedList = Text.Combine(
				              AddSingleQuotes, 
				              ","
				            )
				        in
				          DelimitedList
				    else 
				      //if the parameter isn't a list
				      //just add single quotes around the parameter value
				      "'" & _tag & "'",
				    anchor_date = if _anchor_date = #datetime(9999, 12, 31, 0, 0, 0) then "now()" else "todatetime('" &DateTime.ToText(_anchor_date) & "')",
				    relative_time_period = Text.AfterDelimiter(_relative_time_period, " - "),
				    Query = "
				    let relative_time = '" & relative_time_period & "';
				    let anchor_date = " & anchor_date & ";
				    let start = todatetime('" & DateTime.ToText(_start_date) & "');
				    let end = todatetime('" & DateTime.ToText(_end_date) & "');
				    let _start = iff(relative_time == '*custom*', todatetime(start), anchor_date - totimespan(relative_time));
				    let _end = iff(relative_time == '*custom*', todatetime(end), anchor_date);
				    let _asset = '" &_asset &"';
				    AssetAnomaliesMVADInterpretation
				    | where timestamp  between (_start .. _end) and asset  == _asset and is_anomaly and severity >= " & Number.ToText(_mvad_severity_threshold) & "
				    | mv-expand
				        secondary_tag = correlation_changes.changed_variables to typeof(string),
				        correlation_change = correlation_changes.changed_values to typeof(double)
				    | project-away correlation_changes, is_anomaly
				    | summarize records = count(), weighted_score = 1000 * sum(severity * contribution_score * correlation_change),  
				    average = avg(correlation_change), minimum = min(correlation_change), maximum = max(correlation_change) by tag, secondary_tag",
				    Source = AzureDataExplorer.Contents("https://trd-xarh0n5kkf5xbfcwyc.z4.kusto.fabric.microsoft.com", "MultivariateAnomalyDetectionEH", Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null])
				in
				    Source
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

